site_name: 'Kitupiikki'
site_description: 'Ilmainen kirjanpito-ohjelma'
site_author: 'Arto Hyvättinen'
site_url: 'https://kitupiikki.info'

copyright: 'Copyright &copy; 2017-2019 Arto Hyvättinen'
theme:
  name: null
  custom_dir: material
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  logo: 'images/Possu64.png'
  language: 'fi'
  favicon: 'images/Possu64.png'
  font: 'Roboto'
  mono: 'Ubuntu Mono'
  feature:
    tabs: false
  extra_templates:
    '404.html'
extra:
  disqus: 'Kitupiikki'
  social:
    - type: 'github'
      link: 'https://github.com/artoh/kitupiikki'
    - type: 'youtube'
      link: 'https://www.youtube.com/channel/UCVNHCMQoNb66OgzuTSfdKqQ'
    - type: 'comment'
      link: 'http://palaute.kitupiikki.info'
    - type: 'twitter'
      link: 'https://twitter.com/KitupiikkiInfo'
  search:
    language: 'fi'
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - toc:
        permalink: true
google_analytics:
  - 'UA-92837430-1'
  - 'auto'
pages:
  - Kitupiikki: 'index.md'
  - Esittely:
    - Ominaisuudet: 'esittely.md'
    - Videot: 'videot.md'
    - Käyttöliittymä: 'ui.md'
    - Tuki: 'tuki.md'
  - Kirjanpidosta lyhyesti: 'kirjanpito/index.md'
  - Asennus: 'asennus.md'
  - Kirjanpidon aloittaminen: 'aloitus/index.md'
  - Määritykset:
    - Perusvalinnat: 'maaritykset/perusvalinnat/index.md'
    - Tilikartta: 'maaritykset/tilikartta/index.md'
    - Tositelajit: 'maaritykset/tositelajit/index.md'
    - Kohdennukset: 'maaritykset/kohdennukset/index.md'
    - Tilinavaus : 'maaritykset/tilinavaus/index.md'
    - Laskutus: 'maaritykset/laskutus/index.md'
    - Sähköpostin lähettäminen: 'maaritykset/sahkoposti/index.md'
    - Verkkolasku: 'maaritykset/verkkolasku/index.md'
    - Tuonti : 'maaritykset/tuonti/index.md'
    - Kirjattavien kansio : 'maaritykset/inbox/index.md'
    - Mukauttaminen:
        - Raportit: 'maaritykset/raportit/index.md'
        - Tilinpäätöksen malli: 'maaritykset/tilinpaatos/index.md'
        - Monimuotoiset tilikartat : 'maaritykset/monimuoto/index.md'
  - Kirjaaminen:
    - Kirjaaminen : 'kirjaus/index.md'
    - Kirjausapuri: 'kirjaus/apuri/index.md'
    - Käsin kirjaaminen: 'kirjaus/kasin/index.md'
    - Tuonti: 'kirjaus/tuonti/index.md'
  - Selaaminen ja etsiminen: 'selaus/index.md'
  - Laskutus:
    - Laskutus: 'laskutus/index.md'
    - Uusi lasku: 'laskutus/uusi/index.md'
    - Maksumuistutukset: 'laskutus/muistutus/index.md'
    - Ryhmälasku : 'laskutus/ryhma/index.md'
  - Tulosteet: 'tulosteet/index.md'
  - Arvonlisävero: 
    - Arvolisävero: 'alv/index.md'
    - Mallikirjaukset: 'alv/mallikirjaukset/index.md'
    - Alv-ilmoitus: 'alv/tilitys/index.md'
    - Maksuperusteinen alv: 'alv/maksuperusteinen/index.md'
  - Tilikaudet ja tilinpäätös:
    - Tilikaudet : 'tilikaudet/tilikaudet/index.md'
    - Tilinpäätös: 'tilikaudet/tilinpaatos/index.md'
    - Sähköinen arkisto: 'tilikaudet/arkisto/index.md'
    - Budjetti: 'tilikaudet/budjetti/index.md'
  - Lisenssi: 'lisenssi.md'
extra_css:
  - 'stylesheets/extra.css'
